UnpremierBetting/Areas/Admin/Controllers/SeasonsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using UnpremierBetting.Services.Interfaces;
using UnpremierBetting.Utilities.Attributes;

namespace UnpremierBetting.Areas.Admin.Controllers
{
    [AdminAuthorize]
    [RouteArea("admin")]
    [RoutePrefix("seasons")]
    public class SeasonsController : Controller
    {
        private readonly ISeasonsService service;

        public SeasonsController(ISeasonsService service)
        {
            this.service = service;
        }

        [HttpGet]
        [Route]
        public ActionResult Options()
        {
            this.ViewBag.AllSeasonYears = this.service.GetSeasonsList();
            this.ViewBag.AllLeaguesList = this.service.GetLeaguesList();
            return this.View();
        }

        [HttpPost]
        [Route("generate")]
        public ActionResult Generate(int leagueId, DateTime firstMatchDate)
        {
            if (this.ModelState.IsValid)
            {
                this.service.CreateSeasonMatches(leagueId, firstMatchDate);
                this.service.SimulateSeason(leagueId, firstMatchDate.Year);
            }

            return this.RedirectToAction("Options");
        }

        [HttpPost]
        [Route("delete")]
        public ActionResult Delete(int leagueId, int year)
        {
            this.service.DeleteSeasonMatches(leagueId, year);

            return this.RedirectToAction("Options");
        }

        [HttpPost]
        [Route("league")]
        public ActionResult League(string leagueName)
        {
            this.service.CreateLeague(leagueName);

            return this.RedirectToAction("Options");
        }
    }
}

UnpremierBetting/Controllers/ClubsController.cs
using System.Web.Mvc;
using UnpremierBetting.Models.ViewModels.Clubs;
using UnpremierBetting.Services.Interfaces;

namespace UnpremierBetting.Controllers
{
    [RoutePrefix("clubs")]
    public class ClubsController : Controller
    {
        private readonly IClubsService service;

        public ClubsController(IClubsService service)
        {
            this.service = service;
        }

        [Route("{id}")]
        public ActionResult Details(int id)
        {
            var clubVm = this.service.GetClubDetails(id);

            return this.View(clubVm);
        }

        [ChildActionOnly]
        public ActionResult PlayerInfo(ClubPlayerViewModel playerVm)
        {
            this.ViewBag.LabelColor =
               playerVm.Overall < 40 ? "danger"
                   : playerVm.Overall < 70 ? "warning"
                       : playerVm.Overall < 90 ? "success" : "primary";

            return this.PartialView("_PlayerInfo", playerVm);
        }
    }
}

UnpremierBetting/Controllers/PlayersController.cs
using System.Web.Mvc;
using UnpremierBetting.Models.ViewModels.Players;
using UnpremierBetting.Services.Interfaces;

namespace UnpremierBetting.Controllers
{
    [RoutePrefix("players")]
    public class PlayersController : Controller
    {
        private readonly IPlayersService service;

        public PlayersController(IPlayersService service)
        {
            this.service = service;
        }

        [Route("{playerId}")]
        public ActionResult Details(int playerId)
        {
            PlayerDetailsViewModel playerVm = this.service.GetPlayer(playerId);

            this.ViewBag.LabelColor =
                playerVm.Overall < 40 ? "danger"
                    : playerVm.Overall < 70 ? "warning"
                        : playerVm.Overall < 90 ? "success" : "primary";

            return this.View(playerVm);
        }

        [ChildActionOnly]
        public ActionResult Stats(int leagueId = 0, int year = 0)
        {
            var statVms = this.service.GetStats(leagueId, year);

            return this.PartialView("_Stats", statVms);
        }
    }
}

UnpremierBetting/Controllers/SeasonsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UnpremierBetting.Models.ViewModels.Seasons;
using UnpremierBetting.Services.Interfaces;

namespace UnpremierBetting.Controllers
{
    [RoutePrefix("seasons")]
    public class SeasonsController : Controller
    {
        private readonly ISeasonsService service;

        public SeasonsController(ISeasonsService service)
        {
            this.service = service;
        }

        [Route("table")]
        public ActionResult Table(int leagueId = 0, int year = 0)
        {
            IEnumerable<LeagueTableClubViewModel> clubTableVms = this.service.GetLeagueTable(leagueId, year);

            this.ViewBag.AllLeagues = this.service.GetLeaguesList(l => l.Seasons.Any(s => !s.IsDeleted));
            this.ViewBag.AllSeasonYears = this.service.GetSeasonsList();

            this.ViewBag.SelectedYear = year;
            this.ViewBag.SelectedLeague = leagueId;

            return this.View(clubTableVms);
        }

        [ChildActionOnly]
        public ActionResult TableClub(LeagueTableClubViewModel clubVm, int clubsCount)
        {
            this.ViewBag.Color = 
                clubVm.Position == 1 ? "bg-info"
                : clubVm.Position <= 4 ? "bg-success"
                : clubVm.Position >= clubsCount - 2 ? "bg-danger" : string.Empty;

            return this.PartialView("_TableClub", clubVm);
        }
    }
}

UnpremierBetting/Views/Seasons/Table.cshtml
@using UnpremierBetting.Models.ViewModels
@model IEnumerable<UnpremierBetting.Models.ViewModels.Seasons.LeagueTableClubViewModel>

@{
    ViewBag.Title = "League Table";
}

<h2>@ViewBag.Title</h2>
<h4>Season</h4>

<div class="row">
    @using (Html.BeginForm("Table", "Seasons", FormMethod.Post))
    {
        <div class="col-lg-2">
            @Html.DropDownList("leagueId", (IEnumerable<SelectListItem>)this.ViewBag.AllLeagues, new { @class = "form-control" })
            @Html.DropDownList("year", (IEnumerable<SelectListItem>)this.ViewBag.AllSeasonYears, new { @class = "form-control" })
        </div>
        <div class="col-lg-2">
            <div class="form-group">
                <input type="submit" value="Filter" class="form-control btn btn-info" />
            </div>
        </div>
    }
</div>

<div class="row">
    <div class="col-lg-8">
        <table class="table">
            <tr class="bg-primary">
                <th>Position</th>
                <th>Club</th>
                <th>Matches</th>
                <th>Wins</th>
                <th>Draws</th>
                <th>Losses</th>
                <th>Points</th>
            </tr>

            @{
                foreach (var club in Model)
                {
                    @Html.Action("TableClub", "Seasons", new { clubVm = club, clubsCount = Model.Count() })
                }
            }
        </table>
    </div>
    <div class="col-lg-4">
        @Html.Action("Stats", "Players", new { leagueId = this.ViewBag.SelectedLeague, year = this.ViewBag.SelectedYear })
    </div>
</div>

UnpremierBetting/Views/Seasons/_Stats.cshtml
@model IDictionary<string, IList<UnpremierBetting.Models.ViewModels.Players.PlayerStatisticViewModel>>

<br />
<div class="row">
    <div class="col-lg-12">
        <table class="table">
            <tr class="bg-primary">
                <th>Goals</th>
                <th></th>
                <th></th>
            </tr>
            @foreach (var stat in Model["Goals"])
            {
                <tr>
                    <td>@stat.Position</td>
                    <td>
                        <img src="~/Content/Images/Players/@(stat.PictureId).png" width="@stat.PictureSize">
                        @Html.ActionLink(
                       stat.PlayerName, "Details", "Players", new { playerId = stat.PlayerId }, null)
                    </td>
                    <td class="text-primary" style="font-weight: bold">
                        @stat.StatCount
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

UnpremierBetting/Views/Seasons/_TableClub.cshtml
@using UnpremierBetting.Models.ViewModels
@model UnpremierBetting.Models.ViewModels.Seasons.LeagueTableClubViewModel

<tr class="@this.ViewBag.Color">
    <td>
        @Html.DisplayFor(modelItem => Model.Position)
    </td>
    <td>
        @Html.ActionLink(Model.Name, "Details", "Clubs", new { id = Model.Id }, null)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.MatchesPlayed)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.WinsCount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.DrawsCount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.LossesCount)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Points)
    </td>
</tr>