UnpremierBetting/Controllers/ClubsController.cs
using System.Web.Mvc;
using UnpremierBetting.Models.ViewModels.Clubs;
using UnpremierBetting.Services.Interfaces;

namespace UnpremierBetting.Controllers
{
    [RoutePrefix("clubs")]
    public class ClubsController : Controller
    {
        private readonly IClubsService service;

        public ClubsController(IClubsService service)
        {
            this.service = service;
        }

        [Route("{id}")]
        public ActionResult Details(int id)
        {
            var clubVm = this.service.GetClubDetails(id);

            return this.View(clubVm);
        }

        [ChildActionOnly]
        public ActionResult PlayerInfo(ClubPlayerViewModel playerVm)
        {
            this.ViewBag.LabelColor =
               playerVm.Overall < 40 ? "danger"
                   : playerVm.Overall < 70 ? "warning"
                       : playerVm.Overall < 90 ? "success" : "primary";

            return this.PartialView("_PlayerInfo", playerVm);
        }
    }
}

UnpremierBetting/Controllers/MatchesController.cs
using System.Linq;
using System.Web.Mvc;
using UnpremierBetting.Models.ViewModels.Matches;
using UnpremierBetting.Services.Interfaces;
using UnpremierBetting.Utilities;

namespace UnpremierBetting.Controllers
{
    [RoutePrefix("matches")]
    public class MatchesController : Controller
    {
        private readonly IMatchesService service;
        public MatchesController(IMatchesService service)
        {
            this.service = service;
        }

        [Route("fixtures/{leagueId:int?}/{year:int?}/{page:int?}")]
        public ActionResult Fixtures(int leagueId = 0, int year = 0, int page = 0)
        {
            var fixtureVms = this.service.GetFixtures(leagueId, year);

            this.ViewBag.PageCount = Paginator.GetPagesCount(fixtureVms.Count());
            this.ViewBag.ItemCount = Paginator.ItemsPerPage;
            this.ViewBag.CurrentPage = page == 0 ? Paginator.GetActiveFixturesPage(fixtureVms) : page;

            this.ViewBag.SeasonYear = fixtureVms.First().MatchDay.Year;
            this.ViewBag.AllSeasonYears = this.service.GetSeasonsList();

            this.ViewBag.AllLeaguesList = this.service.GetLeaguesList(l => l.Seasons.Any(s => !s.IsDeleted));

            var pageFixtureVms = Paginator.GetPageItems(fixtureVms, this.ViewBag.CurrentPage);

            return this.View(pageFixtureVms);
        }

        [Authorize]
        [Route("details/{matchId}")]
        public ActionResult Details(int matchId)
        {
            MatchDetailsViewModel matchVm = this.service.GetMatchDetails(matchId);

            return this.View(matchVm);
        }
    }
}

UnpremierBetting/Controllers/SeasonsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using UnpremierBetting.Models.ViewModels.Seasons;
using UnpremierBetting.Services.Interfaces;

namespace UnpremierBetting.Controllers
{
    [RoutePrefix("seasons")]
    public class SeasonsController : Controller
    {
        private readonly ISeasonsService service;

        public SeasonsController(ISeasonsService service)
        {
            this.service = service;
        }

        [Route("table")]
        public ActionResult Table(int leagueId = 0, int year = 0)
        {
            IEnumerable<LeagueTableClubViewModel> clubTableVms = this.service.GetLeagueTable(leagueId, year);

            this.ViewBag.AllLeagues = this.service.GetLeaguesList(l => l.Seasons.Any(s => !s.IsDeleted));
            this.ViewBag.AllSeasonYears = this.service.GetSeasonsList();

            this.ViewBag.SelectedYear = year;
            this.ViewBag.SelectedLeague = leagueId;

            return this.View(clubTableVms);
        }

        [ChildActionOnly]
        public ActionResult TableClub(LeagueTableClubViewModel clubVm, int clubsCount)
        {
            this.ViewBag.Color = 
                clubVm.Position == 1 ? "bg-info"
                : clubVm.Position <= 4 ? "bg-success"
                : clubVm.Position >= clubsCount - 2 ? "bg-danger" : string.Empty;

            return this.PartialView("_TableClub", clubVm);
        }
    }
}

UnpremierBetting/Views/Shared/_AdminArea.cshtml
<li class="dropdown">
    <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" ariahaspopup="true" aria-expanded="false">
        Admin
        <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
        <li>
            @Html.ActionLink("Club Options", "Options", "Clubs",
                routeValues: new { area = "Admin" }, htmlAttributes: null)
        </li>
        <li>
            @Html.ActionLink("Season Options", "Options", "Seasons",
                routeValues: new { area = "Admin" }, htmlAttributes: null)
        </li>
    </ul>
</li>

UnpremierBetting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="icon" href="~/favicon.ico" type="image/ico" />
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Unpremier Betting", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("League Table", "Table", "Seasons", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("Fixtures", "Fixtures", "Matches", new { area = "" }, null)</li>
                </ul>
                @Html.Action("LoginMenu", "Home", new { area = "" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Unpremier Betting</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ajax")
    @RenderSection("scripts", required: false)
</body>
</html>

UnpremierBetting/Views/Shared/_MenuAuthorized.cshtml
@using Microsoft.AspNet.Identity
@using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
{
    @Html.AntiForgeryToken()
    <ul class="nav navbar-nav navbar-right">
        @Html.Action("AdminArea", "Admin", new { area = "Admin" })
        <li>@Html.ActionLink("My Ticket", "Ticket", "Bets", new {area = "Bets"}, null)</li>
        <li>
            @Html.ActionLink("Hello " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })
        </li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log Out</a></li>
    </ul>
}

UnpremierBetting/Views/Shared/_MenuUnAuthorized.cshtml
<ul class="nav navbar-nav navbar-right">
    <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
    <li>@Html.ActionLink("Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
</ul>

UnpremierBetting/Views/Shared/_Popup.cshtml
@model UnpremierBetting.Models.ViewModels.PopupViewModel

<div class="alert alert-@Model.Type">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>@Model.BoldMessage</strong> @Model.Message
</div>